a = input('digite alguma coisa: ')
print('o tipo primitivo desse valor é:',type(a))
print('so tem espaço', a.isspace())
print('so tem numero', a.isnumeric())
print('e alfabetico', a.isalpha())
print('e alfa numerico', a.isalnum())
print(' maiusculo', a.isupper())
print('minusculo', a.islower())
print('capitalizada', a.istitle())